### ISSUE TITLE
Code-breaking issues from tkinter and tkfilebrowser (move to wxPython?)

### ISSUE THREAD

**Issue by pizzaolive** [pizzaolive/ant_upload_checker#34]
* tkinter is not installed by default with some systems e.g. Ubuntu and Python 3.10
* tkfilebrowser is causing issues for some on a Linux system. I've not been able to replicate the issue on Ubuntu, but it seems to be an open issue and as it's no longer maintained, look to move away from use tkinter and tkfilebrowser
* suggest look into wxPython instead

**Comment by pizzaolive** [comment]
Traceback (most recent call last):
  File "/home/user/python_venv/bin/ant-upload-checker", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/python_venv/lib/python3.12/site-packages/ant_upload_checker/main.py", line 12, in main
    setup.save_user_info_to_env()
  File "/home/user/python_venv/lib/python3.12/site-packages/ant_upload_checker/setup.py", line 34, in save_user_info_to_env
    get_user_info_input_folders()
  File "/home/user/python_venv/lib/python3.12/site-packages/ant_upload_checker/setup.py", line 45, in get_user_info_input_folders
    directories = tkfilebrowser.askopendirnames(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/python_venv/lib/python3.12/site-packages/tkfilebrowser/functions.py", line 100, in askopendirnames
    dialog = FileBrowser(parent, mode="opendir", multiple_selection=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/python_venv/lib/python3.12/site-packages/tkfilebrowser/filebrowser.py", line 396, in __init__
    self.left_tree.insert("", "end", iid=l[0],
  File "/usr/lib/python3.12/tkinter/ttk.py", line 1336, in insert
    res = self.tk.call(self._w, "insert", parent, index,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Item /home/user/Videos already exists

**Comment by pizzaolive** [comment]
Traceback (most recent call last):
  File "/Users/secret/miniconda3/envs/ant-checker/bin/ant-upload-checker", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/ant_upload_checker/main.py", line 12, in main
    setup.save_user_info_to_env()
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/ant_upload_checker/setup.py", line 34, in save_user_info_to_env
    get_user_info_input_folders()
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/ant_upload_checker/setup.py", line 45, in get_user_info_input_folders
    directories = tkfilebrowser.askopendirnames(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/tkfilebrowser/functions.py", line 100, in askopendirnames
    dialog = FileBrowser(parent, mode="opendir", multiple_selection=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/tkfilebrowser/filebrowser.py", line 314, in __init__
    wrapper = TooltipTreeWrapper(self.left_tree)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/tkfilebrowser/tooltip.py", line 86, in __init__
    self.tooltip = Tooltip(tree, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/site-packages/tkfilebrowser/tooltip.py", line 47, in __init__
    self.overrideredirect(True)
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/tkinter/__init__.py", line 2252, in wm_overrideredirect
    return self._getboolean(self.tk.call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/secret/miniconda3/envs/ant-checker/lib/python3.12/tkinter/__init__.py", line 1524, in _getboolean
    return self.tk.getboolean(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: expected boolean value but got ""

**Comment by pizzaolive** [comment]
wxPython does not by default install well on Linux either. Keep looking?

**Comment by pizzaolive** [comment]
Hoping this is fixed in 1.6.1 - stopped using tkfilebrowser, solely rely on tkinter now which is maintained.

Provided instructions for Linux users if tkinter is not installed.
